<script lang='ts'>
// @ts-nocheck
    import Variant from '$lib/variants.svelte'
    import Placeholder from '$lib/assets/placeholder.jpeg'
    import Compare from '$lib/compare.svelte'
    import Table from '$lib/table.svelte'
	import { onMount } from 'svelte';
    import { page } from '$app/stores';
    import { dev } from '$app/environment';
    
    import { Button } from 'flowbite-svelte';

    import type { PageData } from './$houdini'
    export let data: PageData

    $: ({ ProductDetails } = data)
	$: console.log("Product deta: ", $ProductDetails)

    onMount(async()=>{
        // Register a Service Worker.
        navigator.serviceWorker.getRegistration('/service-worker.js').then(function (registration) {
		// Use the PushManager to get the user's subscription to the push service.
		return registration.pushManager.getSubscription().then(async function (subscription) {
			// If a subscription was found, return it.
			if (subscription) {
				return subscription;
			}

			// Get the server's public key
			const response =
				'BC7i8ymKPvPQIsOQPZHaF6hv6iBzml0kPIw8Tv3lrrxW_d7y04xaqKyrOwJASFiX1ftkfC4HhOb7kjt-kX97COw';
			const vapidPublicKey = await response;
			// Chrome doesn't accept the base64-encoded (string) vapidPublicKey yet
			// urlBase64ToUint8Array() is defined in /tools.js
			const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey);
			console.log('11');
			// Otherwise, subscribe the user (userVisibleOnly allows to specify that we don't plan to
			// send notifications that don't have a visible effect for the user).
			return registration.pushManager.subscribe({
				userVisibleOnly: true,
				applicationServerKey: convertedVapidKey
			});
		});
	})
	.then(function (subscription) {
		console.log('we are jere');
		// Send the subscription details to the server using the Fetch API.
		console.log(subscription);
		// fetch('./register', {
		//   method: 'post',
		//   headers: {
		//     'Content-type': 'application/json'
		//   },
		//   body: JSON.stringify({
		//     subscription: subscription
		//   }),
		// });

		const convertedVapidKey = urlBase64ToUint8Array(
			`BC7i8ymKPvPQIsOQPZHaF6hv6iBzml0kPIw8Tv3lrrxW_d7y04xaqKyrOwJASFiX1ftkfC4HhOb7kjt-kX97COw`
		);
		console.log(convertedVapidKey);
		fetch('/api/notify/insert', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ sub: subscription, key: convertedVapidKey })
		});
		document.getElementById('doIt').onclick = function () {
			fetch(`/doit?array=${convertedVapidKey}`, { method: 'get' });
			// Ask the server to send the client a notification (for testing purposes, in actual
			// applications the push notification is likely going to be generated by some event
			// in the server).
		};
	});
})


function urlBase64ToUint8Array(base64String) {
	var padding = '='.repeat((4 - (base64String.length % 4)) % 4);
	var base64 = (base64String + padding).replace(/\-/g, '+').replace(/_/g, '/');

	var rawData = window.atob(base64);
	var outputArray = new Uint8Array(rawData.length);

	for (var i = 0; i < rawData.length; ++i) {
		outputArray[i] = rawData.charCodeAt(i);
	}
	return outputArray;
}

    let compareGroup = 'Variant'
    $: console.log("Selected:", compareGroup , variantGroup, typeof(variantGroup))

    $: product = $ProductDetails.data.productCollection.edges[0].node
    $: variants = product.productVariantCollection.edges
    $: quantities = product.productQuantityCollection.edges
    $: stores = variants.map(v => v?.node?.productListingCollection?.edges[0]?.node.store)

    let variantGroup = null
    let variantGroupObject = null
    $: variantGroup = variantGroup ?? variants[0].node
    $: variantGroupObject = variantGroupObject ?? (typeof(variantGroup) === "object" ? variantGroup : null)

    $: console.log("Stores:",stores)

    let formatQuantity = quantity => 
    (quantity.count > 1 ? `${quantity.count}×` : "") + Intl.NumberFormat("en", { style: "unit", unit: quantity.unit }).format(quantity.quantity);

    let formatPrice = price => price ?  Intl.NumberFormat("en", { style: "currency", currency: price?.currency ?? "SAR" }).format(price?.price) : null

    $: rowHeaders = compareGroup !== "Store" ? stores.map(s => s?.name?.en) : variants.map(q => q?.node?.name?.en) 
    $: columnHeaders = compareGroup === "Variant" ? quantities.map(q => formatQuantity(q?.node)) :  variants.map(q => q?.node?.name?.en) 
    let tableData: float[][];
    $: tableData = variantGroupObject.productListingCollection?.edges.map(l => l.node.priceDeltaCollection.edges.map(p => p.node))
    

    $: console.log("Table: ", rowHeaders, columnHeaders, tableData)
</script>

<main>

    <div class='product-image'>
        <img src={variants[variantGroup === "Peach" ? 1 : 0]?.node?.productListingCollection?.edges[0]?.node?.image}>
    </div>
    <div class="product-details">
        <div class="notify">
            <Button color='light'>Notify Me</Button>
        </div>
        
        <h1 class="product-name">{product?.name?.en}</h1>
        <div class="details">
            <div class="brand-container">
                <span class="brand">Brand</span>
                <span class="brand-name">{product?.brand?.name?.en}</span>
            </div>
            <div class="compare-container">
                <p class="compare-text">Compare Prices:</p>
                <!-- Comparison Buttons -->
                <div class="compare-by-container">
                    {#each ['Store', 'Variant', 'Quantity'] as type}
                        <Compare bind:group={compareGroup} {type} />
                    {/each}
                </div>
            </div>
            <div class='variant-container'>
                <div class="variant-listing">
                    {#if compareGroup=='Variant'}
                        {#each variants as {node : variant}}
                            <Variant bind:group={variantGroup} type={'Variant'}, value={variant?.name?.en}, text={variant?.name?.en} src={variant?.productListingCollection?.edges[0]?.node?.image} />
                        {/each}
                    {:else if compareGroup=='Market'}
                        {#each stores as store}
                            <Variant bind:group={variantGroup} type={'Store'}, value={store}, text={store?.name?.en} />
                        {/each}
                    {:else if compareGroup=='Quantity'}
                        {#each quantities as {node : quantity}}
                            <Variant bind:group={variantGroup} type={'Quantity'}, value={quantity?.name?.en}, text={formatQuantity(quantity)} />
                        {/each}
                    {/if}
                </div>  
            </div>
        </div>
    </div>

    <table>
        {#each rowHeaders as row, i}
            {#if i === 0}
                <tr>
                <th />
                {#each columnHeaders as col, j}
                    <th>
                        <div>
                        <span class="header">
                        {col}
                        </span>
                        </div>
                    </th>
                {/each}
                </tr>
            {:else}
                <tr>
                <th>{row}</th>
                {#each columnHeaders as _, j}
                    <td> <div> <span class="value"> {formatPrice(tableData?.[i-1]?.[j]) ?? "-"} </span> </div>  </td>
                {/each}
                </tr>
            {/if}
        {/each}

    </table>

</main>

    


<style>


    table{
        display: flex;
        min-width: var(--max-w-xs, 400px);
        flex-direction: column;
        align-items: flex-start;
        flex: 1 0 0;
        border-radius: 4px;
        background: #363636;
        /* shadow */
        box-shadow: 0px 1px 2px -1px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.10);
    }
    th{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: flex-start;
        flex: 1 0 0;
        align-self: stretch;
        border-top: 1px solid var(--gray-300, #D1D5DB);
        border-right: var(--Boxed, 0px) solid var(--gray-300, #D1D5DB);
        border-bottom: var(--Boxed, 0px) solid var(--gray-300, #D1D5DB);
        border-left: var(--Boxed, 0px) solid var(--gray-300, #D1D5DB);
        background: var(--gray-200, #E5E7EB);
    }

    tr{
        display: flex;
        align-items: flex-start;
        align-self: stretch;
        background: var(--black, #000);
    }

    div{
        display: flex;
        padding: 10px 12px;
        align-items: flex-start;
        align-self: stretch;
        border-radius: var(--Boxed, 0px);
    }
    td{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: flex-start;
        flex: 1 0 0;
        align-self: stretch;
        border-top: 1px solid var(--gray-300, #D1D5DB);
        border-right: var(--Boxed, 0px) solid var(--gray-300, #D1D5DB);
        border-bottom: var(--Boxed, 0px) solid var(--gray-300, #D1D5DB);
        border-left: var(--Boxed, 0px) solid var(--gray-300, #D1D5DB);
        background: var(--gray-50, #F9FAFB);
    }

    .header{
        color: var(--black, #000);
        text-align: center;
        font-family: Inter;
        font-size: 12px;
        font-style: normal;
        font-weight: 600;
        line-height: 130%; /* 15.6px */
    }

    .value{
        flex: 1 0 0;
        color: var(--black, #000);
        font-family: Inter;
        font-size: 12px;
        font-style: normal;
        font-weight: 400;
        line-height: 130%; /* 15.6px */
    }

    .product-image{
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        max-width: 40vw;
    }
    main {
        display: flex;
        widows: 100%;
        padding: 48px;
        justify-content: center;
        align-items: center;
        align-content: center;
        gap: 24px;
        flex: 1 0 0;
        align-self: stretch;
        flex-wrap: wrap;
    }

    .notify {
        display: flex;
        justify-content: flex-start;
        width: 100%;
    }
    .table{
        display: block; 
        padding: 48px;
    }
    .product-details{
        display: flex;
        min-width: 261.999px;
        padding: 10px;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 10px;
        flex: 1 0 0;
    }

    .product-name{
        align-self: stretch;
        color: var(--gray-900, #111928);
        /* leading-tight/text-4xl/font-bold */
        font-family: Inter;
        font-size: 36px;
        font-style: normal;
        font-weight: 700;
        line-height: 125%; /* 45px */
    }

    .details{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 10px;
        align-self: stretch;
        border-radius: var(--Boxed, 0px);
    }

    .brand-container{
        display: flex;
        padding: var(--0, 0px);
        align-items: flex-start;
        gap: var(--2, 8px);
        align-self: stretch;
        border-radius: var(--Boxed, 0px);
    }

    .brand{
        color: var(--gray-900, #111928);
        /* text-base/font-medium */
        font-family: Inter;
        font-size: 16px;
        font-style: normal;
        font-weight: 500;
        line-height: 150%; /* 24px */
    }

    .brand-name{
        flex: 1 0 0;
        color: var(--gray-900, #111928);
        /* text-base/font-bold */
        font-family: Inter;
        font-size: 16px;
        font-style: normal;
        font-weight: 700;
        line-height: 150%; /* 24px */
    }

    .compare-container{
        display: flex;
        padding: var(--0, 0px);
        flex-direction: column;
        align-items: flex-start;
        gap: var(--2, 8px);
        align-self: stretch;
        border-radius: var(--Boxed, 0px);
    }

    .compare-text{
        align-self: stretch;
        color: var(--gray-900, #111928);
        /* text-base/font-medium */
        font-family: Inter;
        font-size: 16px;
        font-style: normal;
        font-weight: 500;
        line-height: 150%; /* 24px */
    }

    .compare-by-container{
        display: flex;
        padding: var(--0, 0px);
        align-items: flex-start;
        align-content: flex-start;
        gap: 12px;
        align-self: stretch;
        flex-wrap: wrap;
        border-radius: var(--Boxed, 0px);
    }

    .variant-container{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: flex-start;
        gap: 10px;
        align-self: stretch;
        border-radius: var(--Boxed, 0px);
    }

    .variant-listing{
        display: flex;
        padding: 0px 16px;
        align-items: flex-start;
        align-content: flex-start;
        gap: 10px;
        align-self: stretch;
        flex-wrap: wrap;
    }

    img{
        max-width: 100%;
		max-height: 100%;
		margin: auto;
    }
</style>
