query CategoryProducts($market: String!, $category: String!) {
  marketCollection(filter: {id: {eq: $market}}) {
    edges {
      node {
        categoryCollection(filter: { parent: { is: NULL }, slug: { eq: $category }}) {
          edges {
            node {
              slug
              name
              productCollection {
                edges {
                  node {
                    ... ProductInfo
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
